### ISSUE TITLE
Stylesheet link

### ISSUE THREAD

**Issue by Milchix** [Texotek/texotek.github.io#1]
Du dödel musst dein styhlesheet so linken:   <link href="style.css" rel="stylesheet">

**Comment by Texotek** [comment]
?

**Comment by Milchix** [comment]
<html>
  <head>
    <title> HTML </title>
    <meta charset="wtf-8">
    <link rel="stylesheet" href="style.css"
    <link href="https://fonts.googleapis.com/css?family=Roboto:500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  </head>
<body>

**Comment by Texotek** [comment]
ja was ist mit dem titel?

**Comment by Milchix** [comment]
`<html>
  <head>
    <title> HTML </title>
    <meta charset="wtf-8">
    <link rel="stylesheet" href="style.css"
    <link href="https://fonts.googleapis.com/css?family=Roboto:500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  </head>
<body>`

**Comment by Milchix** [comment]
> 
> 
> ja was ist mit dem titel?

der bleibt gleich

**Comment by Milchix** [comment]
Du kannst ja nicht dein css dokument mit deinem link aufm pc linken

**Comment by Texotek** [comment]
ich hab ja gelinkt

**Comment by Texotek** [comment]
ahh ok  jetzt funkts aber bilder werden nicht geladen
